# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant DCSys Tools Add-on"
  org.opencontainers.image.description: "Home Assistant DCSys Tools Add-on"
  org.opencontainers.image.source: "https://github.com/Jorre05/dcsys_ha_addons"
args:
  TEMPIO_VERSION: "2021.09.0"
