# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant DCSys Add-on"
  org.opencontainers.image.description: "Home Assistant DCSys Add-on"
args:
  TEMPIO_VERSION: "2021.09.0"
