# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: DCSys Tools add-on
version: "1.0.0"
slug: dcsys-tools
description: DCSys tools add-on
url: "https://github.com/Jorre05/dcsys_ha_addons/tree/main/dcsys"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  github_repository: ""
  ha_hostname: "dcsys.struyve.lan"
  fluvius_hostname: "fluvius.struyve.lan"
  inverter_hostname: "inverter.struyve.lan"
schema:
  github_repository: "str?"
  ha_hostname: "str?"
  fluvius_hostname: "str?"
  inverter_hostname: "str?"
image: "github.com/users/Jorre05/packages/container/package/{arch}-dcsys-tools"
