# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: DCSys add-on
version: "1.0.0"
slug: dcsys
description: DCSys add-on
url: "https://github.com/Jorre05/dcsys_ha_addons"
arch:
  - aarch64
init: false
map:
  - share:rw
options:
  ha_hostname: "dcsys.struyve.lan"
  fluvius_hostname: "fluvius.struyve.lan"
  inverter_hostname: "inverter.struyve.lan"
schema:
  ha_hostname: "str?"
  fluvius_hostname: "str?"
  inverter_hostname: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-dcsys"
