# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: DCSys Tools add-on
version: "1.0.4"
slug: dcsys
description: DCSys tools add-on
url: "https://github.com/Jorre05/dcsys_ha_addons/tree/main/dcsys"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - addon_config:rw
options:
  github_repository: ""
  dcsys_config_root_dir: "/share/dcsys_ha_config"
  ha_hostname: "dcsys.struyve.lan"
  fluvius_hostname: "fluvius.struyve.lan"
  inverter_hostname: "inverter.struyve.lan"
schema:
  github_repository: "str?"
  dcsys_config_root_dir: "str?"
  ha_hostname: "str?"
  fluvius_hostname: "str?"
  inverter_hostname: "str?"
image: "ghcr.io/jorre05/{arch}-dcsys-tools"
