name: "DCSys DNS Server"
version: "1.1.0"
slug: "dcsys-dns"
description: "Home Assistant DNS add-on"
url: "https://github.com/Jorre05/dcsys_ha_addons"
arch:
  - aarch64
  - amd64
init: false
startup: system
host_network: true
map:
  - addon_config:rw 
  - share:rw
backup_exclude:
  - '*/cache'
options:
  github_repository: ""
  dcsys_config_root_dir: "/share/dcsys_ha_config"
  listen_on: ""
schema:
  github_repository: "str?"
  dcsys_config_root_dir: "str?"
  listen_on: "str?"
image: "ghcr.io/jorre05/{arch}-dcsys-dns"
